substitutions:
# Change the disp_name to something you want  
  disp_name: PM12C
# Interval of how often the power is updated
  update_time: 10s
# frequency of local supply 50 or 60Hz
  frequency: 50Hz
#SCT-013-000 100A/50ma - 32498
  gain_ct100A: '26077'
# SCT-013-050 50A/1V - 15420
  gain_ct50A: '15420'
#SCT-013-030 30A/1V - 9210
  gain_ct30A: '8650'
  gain_v: '45581'
  mult_v: '3'

esphome:
  name: power_monitor
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
#  manual_ip:
#    static_ip: 192.168.107.43
    # Set this to the IP address of the router. Often ends with .1
#    gateway: 192.168.107.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
#    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret api_pass

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_user
  password: !secret mqtt_pass

web_server:
  port: 80

spi:
  clk_pin: 18
  miso_pin: 19
  mosi_pin: 23

sensor:
  - platform: wifi_signal
    name: ${disp_name} WiFi
    update_interval: 60s
  - platform: atm90e32
    cs_pin: 5
    phase_a:
      voltage:
        name: ${disp_name} Volts A
        id: ic1Volts
        accuracy_decimals: 1
        filters:
          - multiply: ${mult_v}
      current:
        name: ${disp_name} CT1 Amps
        id: ct1Amps
      gain_voltage: ${gain_v}
# Voltage using a 9VAC power transformer
# Note: If you can not get the voltage correct with the highest gain of 65535, uncomment the 2.0 multiply filter above and lower the gain as needed
      gain_ct: ${gain_ct100A}
    phase_b:
      current:
        name: ${disp_name} CT2 Amps
        id: ct2Amps
      gain_ct: ${gain_ct100A}
# Current calibration using a 100A/50ma SCT-013-000
#      gain_ct: 8650
# Current calibration using a 30A/1V SCT-013-030
    phase_c:
      current:
        name: ${disp_name} CT3 Amps
        id: ct3Amps
      gain_ct: ${gain_ct30A}
# Current calibration using a 30A/1V SCT-013-030
    frequency:
      name: ${disp_name} Freq A
    line_frequency: ${frequency}
    gain_pga: 1X
    update_interval: ${update_time}
  - platform: atm90e32
    cs_pin: 4
    phase_a:
      voltage:
        name: ${disp_name} Volts B
        id: ic2Volts
        accuracy_decimals: 1
        filters:
          - multiply: ${mult_v}
      current:
        name: ${disp_name} CT4 Amps
        id: ct4Amps
      gain_voltage: 45200
      gain_ct: ${gain_ct30A}
# Current calibration using a 30A/1V SCT-013-030
    phase_b:
      current:
        name: ${disp_name} CT5 Amps
        id: ct5Amps
      gain_ct: ${gain_ct30A}
# Current calibration using a 30A/1V SCT-013-030
    phase_c:
      current:
        name: ${disp_name} CT6 Amps
        id: ct6Amps
      gain_ct: ${gain_ct30A}
# Current calibration using a 30A/1V SCT-013-030
    frequency:
      name: ${disp_name} Freq B
    line_frequency: ${frequency}
    gain_pga: 1X
    update_interval: ${update_time}    
  - platform: atm90e32
    cs_pin: 15
    phase_a:
      voltage:
        name: ${disp_name} Volts C
        id: ic3Volts
        accuracy_decimals: 1
        filters:
          - multiply: ${mult_v}
      current:
        name: ${disp_name} CT7 Amps
        id: ct7Amps
      gain_voltage: ${gain_v}
      #gain_ct: ${gain_ct30A} * 595 / 549 
      gain_ct: 9631
# Current calibration using a 30A/1V SCT-013-030
    phase_b:
      current:
        name: ${disp_name} CT8 Amps
        id: ct8Amps
      gain_ct: ${gain_ct30A}
# Current calibration using a 30A/1V SCT-013-030
    phase_c:
      current:
        name: ${disp_name} CT9 Amps
        id: ct9Amps
      gain_ct: ${gain_ct30A}
# Current calibration using a 30A/1V SCT-013-030
    frequency:
      name: ${disp_name} Freq C
    line_frequency: ${frequency}
    gain_pga: 1X
    update_interval: ${update_time}    
  - platform: atm90e32
    cs_pin: 16
    phase_a:
      voltage:
        name: ${disp_name} Volts D
        id: ic4Volts
        accuracy_decimals: 1
        filters:
          - multiply: ${mult_v}
      current:
        name: ${disp_name} CT10 Amps
        id: ct10Amps
      gain_voltage: ${gain_v}
      gain_ct: ${gain_ct30A}
# Current calibration using a 30A/1V SCT-013-030
    phase_b:
      current:
        name: ${disp_name} CT11 Amps
        id: ct11Amps
      gain_ct: ${gain_ct30A}
# Current calibration using a 100A/50ma SCT-013-000      
    phase_c:
      current:
        name: ${disp_name} CT12 Amps
        id: ct12Amps
      gain_ct: ${gain_ct30A}
# Current calibration using a 30A/1V SCT-013-030
    frequency:
      name: ${disp_name} Freq D
    line_frequency: ${frequency}
    gain_pga: 1X
    update_interval: ${update_time}    

  - platform: template
    name: ${disp_name} CT1 Watts
    id: ct1Watts
    lambda: return id(ct1Amps).state * id(ic1Volts).state;
    accuracy_decimals: 0
    unit_of_measurement: W
    icon: "mdi:flash-circle"
    update_interval: ${update_time}         
  - platform: template
    name: ${disp_name} CT2 Watts
    id: ct2Watts
    lambda: return id(ct2Amps).state * id(ic1Volts).state;
    accuracy_decimals: 0
    unit_of_measurement: W
    icon: "mdi:flash-circle"
    update_interval: ${update_time}         
  - platform: template
    name: ${disp_name} CT3 Watts
    id: ct3Watts
    lambda: return id(ct3Amps).state * id(ic1Volts).state;
    accuracy_decimals: 0
    unit_of_measurement: W
    icon: "mdi:flash-circle"
    update_interval: ${update_time}         
  - platform: template
    name: ${disp_name} CT4 Watts
    id: ct4Watts
    lambda: return id(ct4Amps).state * id(ic2Volts).state;
    accuracy_decimals: 0
    unit_of_measurement: W
    icon: "mdi:flash-circle"
    update_interval: ${update_time}         
  - platform: template
    name: ${disp_name} CT5 Watts
    id: ct5Watts
    lambda: return id(ct5Amps).state * id(ic2Volts).state;
    accuracy_decimals: 0
    unit_of_measurement: W
    icon: "mdi:flash-circle"
    update_interval: ${update_time}         
  - platform: template
    name: ${disp_name} CT6 Watts
    id: ct6Watts
    lambda: return id(ct6Amps).state * id(ic2Volts).state;
    accuracy_decimals: 0
    unit_of_measurement: W
    icon: "mdi:flash-circle"
    update_interval: ${update_time}         
  - platform: template
    name: ${disp_name} CT7 Watts
    id: ct7Watts
    lambda: return id(ct7Amps).state * id(ic3Volts).state;
    accuracy_decimals: 0
    unit_of_measurement: W
    icon: "mdi:flash-circle"
    update_interval: ${update_time}         
  - platform: template
    name: ${disp_name} CT8 Watts
    id: ct8Watts
    lambda: return id(ct8Amps).state * id(ic3Volts).state;
    accuracy_decimals: 0
    unit_of_measurement: W
    icon: "mdi:flash-circle"
    update_interval: ${update_time}         
  - platform: template
    name: ${disp_name} CT9 Watts
    id: ct9Watts
    lambda: return id(ct9Amps).state * id(ic3Volts).state;
    accuracy_decimals: 0
    unit_of_measurement: W
    icon: "mdi:flash-circle"
    update_interval: ${update_time}         
  - platform: template
    name: ${disp_name} CT10 Watts
    id: ct10Watts
    lambda: return id(ct10Amps).state * id(ic4Volts).state;
    accuracy_decimals: 0
    unit_of_measurement: W
    icon: "mdi:flash-circle"
    update_interval: ${update_time}         
  - platform: template
    name: ${disp_name} CT11 Watts
    id: ct11Watts
    lambda: return id(ct11Amps).state * id(ic4Volts).state;
    accuracy_decimals: 0
    unit_of_measurement: W
    icon: "mdi:flash-circle"
    update_interval: ${update_time}         
  - platform: template
    name: ${disp_name} CT12 Watts
    id: ct12Watts
    lambda: return id(ct12Amps).state * id(ic4Volts).state;
    accuracy_decimals: 0
    unit_of_measurement: W
    icon: "mdi:flash-circle"
    update_interval: ${update_time}         
    
switch:
  - platform: restart
    name: ${disp_name} Restart  
time:
  - platform: sntp
    id: sntp_time    
